# Generated by Django 4.2.7 on 2025-07-07 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_product',
            field=models.CharField(max_length=200),
        ),
    ]
