import React from 'react';
import './TermsAndConditions.css';

const TermsAndConditions = () => {
  return (
    <div className="terms-container">
      <h1>TERMS AND CONDITIONS</h1>

      <h2>1. GENERAL</h2>
      <ol type="a">
        <li>
          This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
        </li>
        <li>
          This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name{' '}
          <a href="https://www.rajanbusinessideas.com" target="_blank" rel="noopener noreferrer">
            www.rajanbusinessideas.com
          </a>
          (hereinafter referred to as the “Website”) which is owned and operated by Rajan Business Ideas (hereinafter referred to as the “Proprietor”), having its registered office at 12-13-664, Nagarjuna Nagar, Tarnaka, Secunderabad-500017, Telangana, where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns.
        </li>
        <li>
          For the purpose of these Terms of Use (“Terms”), wherever the context so requires,
          <ol type="i">
            <li>
              The term ‘You’ & ‘User’ shall mean any legal person or entity accessing or using the services provided on this Website, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872.
            </li>
            <li>
              The terms ‘We’, ‘Us’, ‘Our’ shall mean the Website and/or the Proprietor, as the context so requires.
            </li>
            <li>
              The term ‘Services’ shall mean the business of helping the entrepreneurs to choose a successful business idea, or get their business idea evaluated and find the probability of success in the current market scenario.
            </li>
            <li>
              The terms ‘Party’ & ‘Parties’ shall respectively be used to refer to the User and the Proprietor individually and collectively, as the context so requires.
            </li>
          </ol>
        </li>
        <li>
          The headings of each section in these Terms are only for the purpose of organizing the various provisions under these Terms in an Orderly manner, and shall not be used by either Party to interpret the provisions contained herein in any manner. Further, it is specifically agreed to by the Parties that the headings shall have no legal or contractual value.
        </li>
        <li>
          The use of this Website by the User is solely governed by these Terms as well as the Privacy Policy and any modifications or amendments made thereto by the Proprietor, from time to time, at its sole discretion. If You continue to browse and use this Website You are agreeing to comply with and be bound by the following terms and conditions of use, which together with Our privacy policy in. The User expressly agrees and acknowledges that the Terms and Policy are co-terminus, and that expiry/termination of either one will lead to the termination of the other, save as provided in Section 5 hereunder.
        </li>
        <li>
          The User unequivocally agrees that these Terms and the aforementioned Policy constitute a legally binding agreement between the User and the Proprietor, and that the User shall be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by the Website, and that the same shall be deemed to be incorporated into these Terms, and shall be treated as part and parcel of the same. The User acknowledges and agrees that no signature or express act is required to make these Terms and the Policy binding on the User, and that the User’s act of visiting the any part of the Website constitutes the User’s full and final acceptance of these Terms and the aforementioned Policy.
        </li>
        <li>
          The Proprietor reserves the sole and exclusive right to amend or modify these Terms without any prior permission or intimation to the User, and the User expressly agrees that any such amendments or modifications shall come into effect immediately. The User has a duty to periodically check the terms and stay updated on its requirements. If the User continues to use the Website following such a change, the User will be deemed to have consented to any and all amendments/modifications made to the Terms. In so far as the User complies with these Terms, it is granted a personal, non-exclusive, non-transferable, revocable, limited privilege to enter and use the Website. If the User does not adhere to the changes, it must stop using the Services. Your continuous use of the Services will signify your acceptance of the changed terms.
        </li>
      </ol>

      <h2>2. REGISTRATION</h2>
      <p>
        To fully avail the Services of the Website and use of it, Registration is not mandatory. You may access the services by signing in as User by providing the following information which shall include but not be limited to Name, Mobile Number, Email id, Date of Birth, and etc. Registration for this application is available only to those above the age of 18 years, barring those “Incompetent to Contract” which inter alia include insolvents. If You are a minor and wish to use the application, You may do so through Your legal guardian and the Proprietor reserves the right to terminate Your account on knowledge of You being a minor and having registered on the application or availing any of its Services. Further, at any time during Your use of this Website, including but not limited to the time of registration, You are solely responsible for protecting the confidentiality of Your username and password, and any activity under the account shall be deemed to have been done by You. In the case that You provide Us with false and/or inaccurate details or We have reason to believe You have done so, We hold the right to permanently suspend Your account. You are responsible for safeguarding your password. You agree that you will not disclose your password to any third party and that you will take sole responsibility for any activities or actions under your account, whether or not you have authorized such activities or actions. You will immediately notify us of any unauthorized use of your account.
      </p>

      <h2>3. SERVICE OVERVIEW</h2>
      <p>
        The Proprietor was launched in September 2014, with a sole objective of helping the entrepreneurs to choose a successful business idea, or get their business idea evaluated and find the probability of success in the current market scenario. It has been observed that only 8% of the start-ups are able to sustain in India, and the remaining start-ups are shut down after a few months, there are several factors that lead to the failure of these start-ups. The Website continuously monitors the start-up scenario in India and continuously improve the Business Ideas that We offer depending on the current business market scenario. The Website continuously try and eliminate the factors which led to the failure of the earlier start-ups in similar verticals. The Website reiterate every aspect of a business idea and try to improve the possibility of success of a business idea by putting the right strategy to execute the business. The Website also evaluate the business ideas and give a detailed report on the percentage possibility of success, and give suggestions to assure a definite success. The Website offers 3 major product categories, they are a) Business Ideas b) Evaluate your Business Idea c) Field Reports d) In few cases we help setup/manage a Business
      </p>

      <h2>4. CONTENT</h2>
      <p>
        All information provided by Users are self-declared and not verified by the Proprietor. You must have the rights and/or permissions to share all Content (text, images, videos, design files, etc.) that you submit to the Website as part of your Profile and all such content must be your own creation. If you violate these policies, you will be solely responsible for your actions and will hold the Website and Proprietor indemnified and harmless against any claims that may arise by third parties. You also warrant that the Website will not need to obtain licenses or pay any kind of royalties to any third-party with respect to your Content. Users, acknowledge and agree that the Website may use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform and display any or all photographs, audio, video and film, posting, listing, order placed or enquiry posted on the Website to create marketing materials (collectively, "Content"), in whole or in part, in any manner or media as the Proprietor sees fit, and the Proprietor does not claim any ownership rights in any such Content. The User agrees and understands that some of the features and content may be restricted to users in India.
      </p>
      <p>
        The Users have a personal, non-exclusive, non-transferable, revocable, limited privilege to access the content on the Website. Users can’t copy, adapt, and modify any content without written permission of the Proprietor.
      </p>

      <h2>5. ELIGIBILITY</h2>
      <ol type="a">
        <li>
          The User represents and warrants that he/she is competent and eligible to enter into legally binding agreements and that he/she has the requisite authority to bind himself/herself to these Terms, as determined solely by the provisions of the Indian Contract Act, 1872. The User may not use the Website if he/she is not competent to contract under the Indian Contract Act, 1872, or is disqualified from doing so by any other applicable law, rule or regulation currently in force.
        </li>
        <li>
          If you are accessing the Website from outside the territory of India, then you must be competent to contract as per the local laws of your location.
        </li>
      </ol>

      <h2>6. TERM</h2>
      <p>
        These Terms shall continue to form a valid and binding contract between the Parties, and shall continue to be in full force and effect until the User continues to access and use the Website.
      </p>
      <p>
        A User may terminate his/her use of the Website at any time. The Proprietor may terminate these Terms and close a User account at any time without notice and/or suspend or terminate a User’s access to the Website at any time and for any reason, in its sole discretion. Such suspension or termination shall not limit our right to take any other action against you that we consider appropriate.
      </p>
      <p>
        It is also hereby declared that the Proprietor may discontinue the website without any prior notice.
      </p>

      <h2>7. TERMINATION</h2>
      <p>
        The Proprietor reserves the right, in its sole discretion, to unilaterally terminate the User’s access to the software as a service offered on the Website, or any portion thereof, at any time, without notice or cause. The Website also reserves the universal right to deny access to particular users to any/all of its Services without any prior notice/explanation in order to protect the interests of the Website and/or other visitors to the Website. The Website reserves the right to limit, deny or create different access to the Website and its features with respect to different user(s), or to change any of the features or introduce new features without prior notice. The User shall continue to be bound by these Terms, and it is expressly agreed to by the Parties that the User shall not have the right to terminate these Terms till the expiry of the same, as described in Clause 5 hereinabove.
      </p>

      <h2>8. COMMUNICATION</h2>
      <p>
        By using this Website, and providing his/her contact information to the Proprietor through the Website, the User hereby agrees and consents to receiving calls, autodialed and/or pre-recorded message calls, e-mails and SMSs from the Proprietor and/or any of its affiliates or partners at any time, subject to the Policy. In the event that the User wishes to stop receiving any such marketing or promotional calls/email messages/text messages, the User may send an e-mail to the effect to{' '}
        <a href="mailto:unsubscribe@rajanbusinessideas.com">unsubscribe@rajanbusinessideas.com</a>{' '}
        with the subject [Unsubscribe]. The User agrees and acknowledges that it may take up to fifteen (15) business days for the Proprietor to give effect to such a request by the User. The User expressly agrees that notwithstanding anything contained hereinabove, it may be contacted by the Proprietor or any of its affiliates/partners relating to any service availed of by the User on the Website or anything pursuant thereto. It is expressly agreed to by the Parties that any information shared by the User with the Proprietor shall be governed by the Policy.
      </p>

      <h2>9. CHARGES</h2>
      <p>
        The membership of this Website is free and this includes the browsing of the site and the use of the services. However, We reserve the right to amend the charges for the services rendered. In a case that such happens, Users will be intimated of the same, and it will be up to you to decide whether or not you will continue with services offered by us. Such changes are effective as soon as they are posted on the Site.
      </p>

      <h2>10. USER OBLIGATIONS</h2>
      <p>
        The User agrees and acknowledges that he/she is a restricted User of this Website, and that he/she:
      </p>
      <ol type="a">
        <li>
          Agrees to provide genuine credentials during the process of registration on the Website. You shall not use a fictitious identity to register. We are not liable if the User has provided incorrect information. Agrees to ensure the email address and mobile number provided during account Registration are valid at all times and shall keep your contact information accurate and up-to-date. In Case of change in mobile number, the User will have to create a new User account. The User can update his/her email id anytime, the User has to notify the Website by writing an email to{' '}
          <a href="mailto:support@rajanbusinessideas.com">support@rajanbusinessideas.com</a>
        </li>
        <li>
          Agrees that he/she are solely responsible for maintaining the confidentiality of your account password. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to close your account at any time for any or no reason.
        </li>
        <li>
          Understands and acknowledges that the data submitted is manually entered in to the database of the Website and all data in the Website should be backed by hard copies or appropriate evidence for the purpose of verifying the validity of the data. The user also acknowledges the fact that data so entered into the database is for the purpose of easy and ready reference alone.
        </li>
        <li>
          Authorizes the Website to use, store or otherwise process Your personal information for marketing and promotional purposes.
        </li>
        <li>
          Understands and agrees that, to the fullest extent permissible by law, the Website and their successors and assigns, or any of their affiliates or their respective officers, directors, employees, agents, licensors, representatives, operational service providers, advertisers or suppliers shall not be liable for any loss or damage, of any kind, direct or indirect, in connection with or arising from use of the Website or from this terms of use, including, but not limited to, compensatory, consequential, incidental, indirect, special or punitive damages.
        </li>
        <li>
          Is bound not to cut, copy, modify, recreate, reverse engineer, distribute, disseminate, post, publish or create derivative works from, transfer, or sell any information or obtained from the Website. Any such use/limited use of the Website will only be allowed with the prior express written permission of the Proprietor. For the removal of doubt, it is clarified that unlimited or wholesale reproduction, copying of the content for commercial or non-commercial purposes and unwarranted modification of data and information contained on the Website is expressly prohibited.
        </li>
        <li>
          Agrees not to access (or attempt to access) the Website and/or the materials or services by any means other than through the interface provided by the Website. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website or its content, or in any way reproduce or circumvent the navigational structure or presentation of the Website, materials or any content, or to obtain or attempt to obtain any materials, documents or information through any means not specifically made available through the Website will lead to suspension or termination of the User’s access to the Website, as detailed in Section 11 herein below. The User acknowledges and agrees that by accessing or using the Website or any of the services provided therein, it may be exposed to content that it may consider offensive, indecent or otherwise objectionable. The Proprietor disclaims any and all liabilities arising in relation to such offensive content on the Website. The User expressly agrees and acknowledges that the services displayed on the Website may not be owned by the Proprietor, and that the same may be the exclusive property of certain third parties who have chosen to market their services through the Proprietor’s Website, and that the Proprietor is in no way responsible for the content of the same. The User may however report any such offensive or objectionable content, which the Proprietor may then remove from the Website, at its sole discretion.
        </li>
        <li>
          In places where Website permits the User to post, or upload data/information, the User undertakes to ensure that such material is not offensive or objectionable, and is in accordance with applicable laws. The User expressly agrees that any such material that is deemed to be objectionable/offensive may be removed from the Website immediately and without notice, and further that the User’s access to the Website may also be permanently revoked, at the sole discretion of the Proprietor.
        </li>
        <li>
          Further undertakes not to:
          <ol type="i">
            <li>
              Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal rights of any other person or entity;
            </li>
            <li>
              Engage in any activity that interferes with or disrupts access to the Website or the services provided therein (or the servers and networks which are connected to the Website);
            </li>
            <li>
              Impersonate any person or entity, or falsely state or otherwise misrepresent his/her affiliation with a person or entity;
            </li>
            <li>
              Publish, post, disseminate, any information which is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, pedophilic, libelous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever under any law, rule or regulation currently in force; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;
            </li>
            <li>
              Post any image/file/data that infringes the copyright, patent or trademark of another person or legal entity;
            </li>
            <li>
              Upload or distribute files that contain viruses, corrupted files, or any other similar software or programs that may damage the operation of the Website;
            </li>
            <li>
              Download any file posted/uploaded by another User of the Website that the User is aware, or should reasonably be aware, cannot be legally distributed in such a manner;
            </li>
            <li>
              Probe, scan or test the vulnerability of the Website or any network connected to the Website, nor breach the security or authentication measures on the Website or any network connected to the Website. The User may not reverse look-up, trace or seek to trace any information relating to any other User of, or visitor to, the Website, or any other Customer of the Website, including any User account maintained on the Website not operated/managed by the User, or exploit the Website or information made available or offered by or through the Website, in any manner;
            </li>
            <li>
              Disrupt or interfere with the security of, or otherwise cause harm to, the Website, systems resources, accounts, passwords, servers or networks connected to or accessible through the Website or any affiliated or linked platforms;
            </li>
            <li>
              Collect or store data about other Users of the Website.
            </li>
            <li>
              Use the Website or any material or content therein for any purpose that is unlawful or prohibited by these Terms, or to solicit the performance of any illegal activity or other activity which infringes the rights of this Website or any other third party (ies);
            </li>
            <li>
              Violate any code of conduct or guideline which may be applicable for or to any particular service offered on the Website;
            </li>
            <li>
              Violate any applicable laws, rules or regulations currently in force within or outside India;
            </li>
            <li>
              Violate any portion of these Terms or the Policy, including but not limited to any applicable additional terms of the Website contained herein or elsewhere, whether made by amendment, modification, or otherwise;
            </li>
            <li>
              Threaten the unity, integrity, defense, security or sovereignty of India, friendly relations with foreign states, or public Order, or cause incitement to the commission of any cognizable offence, or prevent the investigation of any offence, or insult any other nation.
            </li>
            <li>
              Publish, post, or disseminate information that is false, inaccurate or misleading;
            </li>
            <li>
              Directly or indirectly offer, attempt to offer, trade, or attempt to trade, any item the dealing of which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation or guideline for the time being in force.
            </li>
            <li>
              Commit any act that causes the Proprietor to lose (in whole or in part) the services of its Internet Establishment ("ISP") or in any manner disrupts the services of any other supplier/service provider of the Proprietor/Website;
            </li>
            <li>
              Engage in advertising to, or solicitation of, other Users of the Website to buy or sell any products or services not currently displayed on the Website. The User may not transmit any chain letters or unsolicited commercial or junk email/messages to other Users via the Website. It shall be a violation of these Terms to use any information obtained from the Website in Order to harass, abuse, or harm another person, or in Order to contact, advertise to, solicit, or sell to another User of the Website without the express prior written consent of the Proprietor.
            </li>
          </ol>
        </li>
      </ol>
      <p>
        The User hereby expressly authorizes the Proprietor/Website to disclose any and all information relating to the User in the possession of the Proprietor/Website to law enforcement or other government officials, as the Proprietor may in its sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those involve personal injury and theft/infringement of intellectual property. The User further understands that the Proprietor/Website might be directed to disclose any information (including the identity of persons providing information or materials on the Website) as necessary to satisfy any judicial Order, law, regulation or valid governmental request.
      </p>

      <h2>11. SUSPENSION OF USER ACCESS AND ACTIVITY</h2>
      <p>
        Notwithstanding other legal remedies that may be available to it, the Proprietor may in its sole discretion limit the User’s access and/or activity by immediately removing the User’s access credentials either temporarily or indefinitely, or suspend/terminate the User’s association with the Website, and/or refuse to usage of the application to the User, without being required to provide the User with notice or cause:
      </p>
      <ol type="a">
        <li>If the User is in breach any of these Terms or the Policy;</li>
        <li>If the User has provided wrong, inaccurate, incomplete or incorrect information;</li>
        <li>If the User’s actions may cause any harm, damage or loss to the other Users or to the Website/Proprietor, at the sole discretion of the Proprietor.</li>
      </ol>

      <h2>12. INDEMNITY</h2>
      <ol type="a">
        <li>
          You agree to indemnify, defend and hold harmless the Proprietor/Website, its independent service providers, and consultants, and their respective directors, officers, employees and agents (collectively, "Parties"), from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by us that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by you pursuant to these terms of use. further, you agree to hold us harmless against any claims made by any third party due to, or arising out of, or in connection with:
          <ol type="i">
            <li>Your use of the website,</li>
            <li>Any Discussions or Messages you provide;</li>
            <li>Your violation of these Terms and Conditions;</li>
            <li>Your violation of any rights of another;</li>
            <li>Your conduct in connection with the Website; or</li>
          </ol>
        </li>
        <li>
          You agree to fully cooperate in indemnifying Us at Your expense. You also agree not to reach a settlement with any party without Our consent.
        </li>
      </ol>
      <p>
        In no event shall the Proprietor/Website be liable to compensate the User or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable, and whether or not the Proprietor/Website had been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortuous action, or any other claim arising out of or in connection with the User’s use of or access to the Website and/or the services or materials contained therein.
      </p>

      <h2>13. LIMITATION OF LIABILITY</h2>
      <ol type="a">
        <li>
          The Founders/ Promoters/ Associated people of the Website are not responsible any consequences arising out of the following events:
          <ol type="i">
            <li>
              If the Website is inoperative/non-responsive due to any connectivity errors associated with the internet connection such as but not limited to slow connectivity, no connectivity, server failure.
            </li>
            <li>
              if the User has fed incorrect figures or data or for any deletion of data
            </li>
            <li>
              if there is undue delay or inability to communicate through email
            </li>
            <li>
              if there is undue delay or inability to synchronize data between the Website and Application or vice versa
            </li>
            <li>
              if there is a failure in the functioning of any other service provided by the Website.
            </li>
          </ol>
        </li>
        <li>
          The Website accepts no liability for any errors or omissions, whether on behalf of itself or third parties, or for any damage caused to the User, the User’s belongings, or any third party, resulting from the use or misuse of the Website or any product purchased or service availed of by the User through the Website. The service and any content or material displayed on the service is provided without any guarantees, conditions or warranties as to its accuracy, suitability, completeness or reliability. The Website will not be liable to you for the unavailability or failure of the Website.
        </li>
        <li>
          Users may be held legally responsible for damages suffered by other Users, the Website or any third party as a result of legally actionable or defamatory comments, remarks, or other information or content posted to the Website.
        </li>
        <li>
          Users are to comply with all laws applicable to them or to their activities, and with all Policies, which are hereby incorporated into this Agreement by reference.
        </li>
        <li>
          The Website expressly excludes any liability for any loss or damage that was not reasonably foreseeable by the Website and which is incurred by you in connection with the website, including loss of profits; and any loss or damage incurred by you as a result of your breach of these terms.
        </li>
        <li>
          To the fullest extent permitted by law, the Website shall not be liable to you or any other party for any loss or damage, regardless of the form of action or basis of any claim. You acknowledge and agree that your sole and exclusive remedy for any dispute with us is to terminate your use of the Website.
        </li>
        <li>
          The development and the maintenance of the Website is done by third party, the founder or the director of the Proprietor are in no way liable for any disputes arising due to the development or maintenance of the Website.
        </li>
      </ol>

      <h2>14. INTELLECTUAL PROPERTY RIGHTS</h2>
      <p>
        Unless expressly agreed to in writing, nothing contained herein shall give the User a right to use any of the Website’s trade names, trademarks, service marks, logos, domain names, information, questions, answers, solutions, reports and other distinctive brand features, save according to the provisions of these Terms. All logos, trademarks, brand names, service marks, domain names, including material, designs, and graphics created by and developed by the Website and other distinctive brand features of the Website are the property of the Proprietor. Furthermore, with respect to the Website created by the Proprietor, the Proprietor shall be the exclusive owner of all the designs, graphics and the like, related to the Website.
      </p>
      <p>
        The User may not use any of the intellectual property displayed on the Website in any manner that is likely to cause confusion among existing or prospective Users of the Website, or that in any manner disparages or discredits the Proprietor/Website, to be determined in the sole discretion of the Proprietor.
      </p>
      <p>
        The User is aware all intellectual property, including but not limited to copyrights, relating to said services resides with the said owners, and that at no point does any such intellectual property stand transferred from the aforementioned creators to the Proprietor, or to the User. The User is aware that the Proprietor merely provides a Website through which the aforementioned services are listed for sale to the Users of the Website, and the neither the Proprietor nor the Website owns any of the intellectual property relating to the services displayed on the Website.
      </p>
      <p>
        The User is further aware that any reproduction or infringement of the intellectual property of the aforementioned owners by the User will result in legal action being initiated against the User by the respective owners of the intellectual property so reproduced/infringed upon. It is agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
      </p>

      <h2>15. DISCLAIMER OF WARRANTIES AND LIABILITIES</h2>
      <ol type="a">
        <li>
          Except as otherwise expressly stated on the Website, all services offered on the Website are offered on an "as is" basis without any warranty whatsoever, either express or implied.
        </li>
        <li>
          The User agrees and undertakes that it is accessing the Website and transacting at his/her sole risk and are that it is using his/her best and prudent judgment before availing any service listed on the Website, or accessing/using any information displayed thereon.
        </li>
        <li>
          The User agrees that any kind of information, resources, activities, recommendations obtained/availed from website, written or oral, will not create any warranty and the Website disclaims all liabilities resulting from these. You are solely responsible for your communication/interaction with other Users on the Website and the Website doesn’t make any warranty about the conduct of Users on the Website.
        </li>
        <li>
          The Proprietor/Website does not guarantee that the functions and services contained in the Website will be uninterrupted or error-free, or that the Website or its server will be free of viruses or other harmful components, and the User hereby expressly accepts any and all associated risks involved with the User’s use of the Website.
        </li>
        <li>
          The Website may avail services from third party to serve you better and these services will be provided on “as is” basis and the Website disclaims any liabilities resulting from these third party services. The Website will not be responsible for any internet delays and damages caused by such problems.
        </li>
        <li>
          It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
        </li>
      </ol>

      <h2>15. RETURNS AND CANCELLATIONS</h2>
      <p>
        All the transactions made on the Website are final and non-refundable. If you believe your purchase was made in error or by fraud, please contact our support staff and they will investigate further and help resolve the matter.
      </p>

      <h2>16. FORCE MAJEURE</h2>
      <p>
        Neither the Proprietor nor the Website shall be liable for damages for any delay or failure to perform its obligations hereunder if such delay or failure is due to cause beyond its control or without its fault or negligence, due to Force Majeure events including but not limited to acts of war, acts of God, earthquake, riot, sabotage, labor shortage or dispute, internet interruption, technical failure, breakage of sea cable, hacking, piracy, cheating, illegal or unauthorized.
      </p>

      <h2>17. FEES AND PAYMENT</h2>
      <p>
        The fees we charge for using our Services are listed on our services page in the Website. We may change our fees from time to time with no advance notice required. The Website uses third Party payment gateway CC Avenue payment to handle financial transactions on the Website. We are not responsible for these third Party services. Such services are depended on the respective third party legal terms. The billing details provided during payment should be up-to-date, such as the billing address and the Users name. Payment information on the website of users using our services is stored on the database for the respective website as encrypted using basic encryption of which can be decrypted to reveal the original information. This information is provided to us by the third Party payment gateway services w use to provide online payment functionality, and hence, may contain certain personal information. We are not responsible for what information is sent to us and it’s stored as this is sent to us via third Party and we cannot control the information sent. However, storage of this information is necessary for legalities and auditing as well as for verification and more. Currently, the information stored that may be deemed personal to the User is their first name, last name and their address zip code.
      </p>
      <p>
        If you wish to dispute a payment regarding your account, you may talk to our Support staff directly.
      </p>
      <p>
        In case the transaction is not processed by the User and the Product has been delivered, the User is liable to make sure that the payment is made.
      </p>

      <h2>18. DISPUTE RESOLUTION AND JURISDICTION</h2>
      <p>
        It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of these Terms and any disputes arising there from will be resolved through a two-step Alternate Dispute Resolution (“ADR”) mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Terms and/or Policy.
      </p>
      <ol type="a">
        <li>
          Mediation: In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed herein below;
        </li>
        <li>
          Arbitration. In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the Proprietor, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be the city of Secunderabad, India;
        </li>
      </ol>
      <p>
        The Parties expressly agree that the Terms, Policy and any other agreements entered into between the Parties are governed by the laws, rules and regulations of India.
      </p>

      <h2>19. NOTICES</h2>
      <p>
        Any and all communication relating to any dispute or grievance experienced by the User may be communicated to the Proprietor by the User writing an email to{' '}
        <a href="mailto:helpdesk@rajanbusinessideas.com">helpdesk@rajanbusinessideas.com</a>.
      </p>

      <h2>20. MISCELLANEOUS PROVISIONS</h2>
      <ol type="a">
        <li>
          Entire Agreement: These Terms, read with the Policy form the complete and final contract between the User and the Proprietor with respect to the subject matter hereof and supersedes all other communications, representations and agreements (whether oral, written or otherwise) relating thereto.
        </li>
        <li>
          Waiver: The failure of either Party at any time to require performance of any provision of these Terms shall in no manner affect such Party's right at a later time to enforce the same. No waiver by either Party of any breach of these Terms, whether by conduct or otherwise, in any one or more instances, shall be deemed to be or construed as a further or continuing waiver of any such breach, or a waiver of any other breach of these Terms.
        </li>
        <li>
          Severability: If any provision/clause of these Terms is held to be invalid, illegal or unenforceable by any court or authority of competent jurisdiction, the validity, legality and enforceability of the remaining provisions/clauses of these Terms shall in no way be affected or impaired thereby, and each such provision/clause of these Terms shall be valid and enforceable to the fullest extent permitted by law. In such case, these Terms shall be reformed to the minimum extent necessary to correct any invalidity, illegality or unenforceability, while preserving to the maximum extent the original rights, intentions and commercial expectations of the Parties hereto, as expressed herein.
        </li>
        <li>
          Contact Us: If you have any questions about this Agreement, the practices of the Website, or your experience with the Service, you can e-mail us at{' '}
          <a href="mailto:team@rajanbusinessideas.com">team@rajanbusinessideas.com</a>.
        </li>
      </ol>
    </div>
  );
};

export default TermsAndConditions;
